export const STARTER_DECK = [
  { id: "starter-001", hanzi: "你好", pinyin: "nǐ hǎo", meaning: "안녕", category: "인사" },
  { id: "starter-002", hanzi: "谢谢", pinyin: "xièxie", meaning: "고마워", category: "인사" },
  { id: "starter-003", hanzi: "对不起", pinyin: "duìbuqǐ", meaning: "미안해", category: "인사" },
  { id: "starter-004", hanzi: "请", pinyin: "qǐng", meaning: "부탁해, please", category: "인사" },
  { id: "starter-005", hanzi: "再见", pinyin: "zàijiàn", meaning: "또 봐, 안녕", category: "인사" },
  { id: "starter-006", hanzi: "是", pinyin: "shì", meaning: "~이다", category: "기초" },
  { id: "starter-007", hanzi: "不是", pinyin: "bú shì", meaning: "~이 아니다", category: "기초" },
  { id: "starter-008", hanzi: "有", pinyin: "yǒu", meaning: "있다, 가지다", category: "기초" },
  { id: "starter-009", hanzi: "没有", pinyin: "méiyǒu", meaning: "없다", category: "기초" },
  { id: "starter-010", hanzi: "可以", pinyin: "kěyǐ", meaning: "~해도 된다, 할 수 있다", category: "기초" },
  { id: "starter-011", hanzi: "我", pinyin: "wǒ", meaning: "나", category: "대명사" },
  { id: "starter-012", hanzi: "你", pinyin: "nǐ", meaning: "너", category: "대명사" },
  { id: "starter-013", hanzi: "他", pinyin: "tā", meaning: "그", category: "대명사" },
  { id: "starter-014", hanzi: "她", pinyin: "tā", meaning: "그녀", category: "대명사" },
  { id: "starter-015", hanzi: "我们", pinyin: "wǒmen", meaning: "우리", category: "대명사" },
  { id: "starter-016", hanzi: "他们", pinyin: "tāmen", meaning: "그들", category: "대명사" },
  { id: "starter-017", hanzi: "这", pinyin: "zhè", meaning: "이것", category: "지시어" },
  { id: "starter-018", hanzi: "那", pinyin: "nà", meaning: "저것", category: "지시어" },
  { id: "starter-019", hanzi: "什么", pinyin: "shénme", meaning: "무엇", category: "질문" },
  { id: "starter-020", hanzi: "谁", pinyin: "shéi", meaning: "누구", category: "질문" },
  { id: "starter-021", hanzi: "哪里", pinyin: "nǎlǐ", meaning: "어디", category: "질문" },
  { id: "starter-022", hanzi: "为什么", pinyin: "wèishénme", meaning: "왜", category: "질문" },
  { id: "starter-023", hanzi: "怎么", pinyin: "zěnme", meaning: "어떻게", category: "질문" },
  { id: "starter-024", hanzi: "哪个", pinyin: "nǎge", meaning: "어느 것", category: "질문" },
  { id: "starter-025", hanzi: "想", pinyin: "xiǎng", meaning: "원하다, 생각하다", category: "동사" },
  { id: "starter-026", hanzi: "知道", pinyin: "zhīdào", meaning: "알다", category: "동사" },
  { id: "starter-027", hanzi: "觉得", pinyin: "juéde", meaning: "느끼다, 생각하다", category: "동사" },
  { id: "starter-028", hanzi: "喜欢", pinyin: "xǐhuan", meaning: "좋아하다", category: "동사" },
  { id: "starter-029", hanzi: "爱", pinyin: "ài", meaning: "사랑하다", category: "동사" },
  { id: "starter-030", hanzi: "认识", pinyin: "rènshi", meaning: "알다, 알게 되다", category: "동사" },
  { id: "starter-031", hanzi: "学习", pinyin: "xuéxí", meaning: "공부하다", category: "동사" },
  { id: "starter-032", hanzi: "工作", pinyin: "gōngzuò", meaning: "일하다, 일", category: "동사" },
  { id: "starter-033", hanzi: "吃", pinyin: "chī", meaning: "먹다", category: "동사" },
  { id: "starter-034", hanzi: "喝", pinyin: "hē", meaning: "마시다", category: "동사" },
  { id: "starter-035", hanzi: "看", pinyin: "kàn", meaning: "보다", category: "동사" },
  { id: "starter-036", hanzi: "听", pinyin: "tīng", meaning: "듣다", category: "동사" },
  { id: "starter-037", hanzi: "说", pinyin: "shuō", meaning: "말하다", category: "동사" },
  { id: "starter-038", hanzi: "读", pinyin: "dú", meaning: "읽다", category: "동사" },
  { id: "starter-039", hanzi: "写", pinyin: "xiě", meaning: "쓰다", category: "동사" },
  { id: "starter-040", hanzi: "去", pinyin: "qù", meaning: "가다", category: "동사" },
  { id: "starter-041", hanzi: "来", pinyin: "lái", meaning: "오다", category: "동사" },
  { id: "starter-042", hanzi: "回", pinyin: "huí", meaning: "돌아오다", category: "동사" },
  { id: "starter-043", hanzi: "买", pinyin: "mǎi", meaning: "사다", category: "동사" },
  { id: "starter-044", hanzi: "卖", pinyin: "mài", meaning: "팔다", category: "동사" },
  { id: "starter-045", hanzi: "开", pinyin: "kāi", meaning: "열다, 시작하다", category: "동사" },
  { id: "starter-046", hanzi: "关", pinyin: "guān", meaning: "닫다", category: "동사" },
  { id: "starter-047", hanzi: "等", pinyin: "děng", meaning: "기다리다", category: "동사" },
  { id: "starter-048", hanzi: "帮助", pinyin: "bāngzhù", meaning: "돕다", category: "동사" },
  { id: "starter-049", hanzi: "问", pinyin: "wèn", meaning: "묻다", category: "동사" },
  { id: "starter-050", hanzi: "回答", pinyin: "huídá", meaning: "대답하다", category: "동사" },
  { id: "starter-051", hanzi: "今天", pinyin: "jīntiān", meaning: "오늘", category: "시간" },
  { id: "starter-052", hanzi: "明天", pinyin: "míngtiān", meaning: "내일", category: "시간" },
  { id: "starter-053", hanzi: "昨天", pinyin: "zuótiān", meaning: "어제", category: "시간" },
  { id: "starter-054", hanzi: "现在", pinyin: "xiànzài", meaning: "지금", category: "시간" },
  { id: "starter-055", hanzi: "早上", pinyin: "zǎoshang", meaning: "아침", category: "시간" },
  { id: "starter-056", hanzi: "中午", pinyin: "zhōngwǔ", meaning: "점심때", category: "시간" },
  { id: "starter-057", hanzi: "晚上", pinyin: "wǎnshang", meaning: "저녁, 밤", category: "시간" },
  { id: "starter-058", hanzi: "时间", pinyin: "shíjiān", meaning: "시간", category: "시간" },
  { id: "starter-059", hanzi: "小时", pinyin: "xiǎoshí", meaning: "시간(hour)", category: "시간" },
  { id: "starter-060", hanzi: "分钟", pinyin: "fēnzhōng", meaning: "분(minute)", category: "시간" },
  { id: "starter-061", hanzi: "一", pinyin: "yī", meaning: "1", category: "숫자" },
  { id: "starter-062", hanzi: "二", pinyin: "èr", meaning: "2", category: "숫자" },
  { id: "starter-063", hanzi: "三", pinyin: "sān", meaning: "3", category: "숫자" },
  { id: "starter-064", hanzi: "四", pinyin: "sì", meaning: "4", category: "숫자" },
  { id: "starter-065", hanzi: "五", pinyin: "wǔ", meaning: "5", category: "숫자" },
  { id: "starter-066", hanzi: "六", pinyin: "liù", meaning: "6", category: "숫자" },
  { id: "starter-067", hanzi: "七", pinyin: "qī", meaning: "7", category: "숫자" },
  { id: "starter-068", hanzi: "八", pinyin: "bā", meaning: "8", category: "숫자" },
  { id: "starter-069", hanzi: "九", pinyin: "jiǔ", meaning: "9", category: "숫자" },
  { id: "starter-070", hanzi: "十", pinyin: "shí", meaning: "10", category: "숫자" },
  { id: "starter-071", hanzi: "大", pinyin: "dà", meaning: "크다", category: "형용사" },
  { id: "starter-072", hanzi: "小", pinyin: "xiǎo", meaning: "작다", category: "형용사" },
  { id: "starter-073", hanzi: "多", pinyin: "duō", meaning: "많다", category: "형용사" },
  { id: "starter-074", hanzi: "少", pinyin: "shǎo", meaning: "적다", category: "형용사" },
  { id: "starter-075", hanzi: "好", pinyin: "hǎo", meaning: "좋다", category: "형용사" },
  { id: "starter-076", hanzi: "忙", pinyin: "máng", meaning: "바쁘다", category: "형용사" },
  { id: "starter-077", hanzi: "累", pinyin: "lèi", meaning: "피곤하다", category: "형용사" },
  { id: "starter-078", hanzi: "快", pinyin: "kuài", meaning: "빠르다", category: "형용사" },
  { id: "starter-079", hanzi: "慢", pinyin: "màn", meaning: "느리다", category: "형용사" },
  { id: "starter-080", hanzi: "高兴", pinyin: "gāoxìng", meaning: "기쁘다", category: "형용사" },
  { id: "starter-081", hanzi: "学校", pinyin: "xuéxiào", meaning: "학교", category: "장소" },
  { id: "starter-082", hanzi: "老师", pinyin: "lǎoshī", meaning: "선생님", category: "사람" },
  { id: "starter-083", hanzi: "学生", pinyin: "xuésheng", meaning: "학생", category: "사람" },
  { id: "starter-084", hanzi: "朋友", pinyin: "péngyou", meaning: "친구", category: "사람" },
  { id: "starter-085", hanzi: "家", pinyin: "jiā", meaning: "집, 가족", category: "장소" },
  { id: "starter-086", hanzi: "公司", pinyin: "gōngsī", meaning: "회사", category: "장소" },
  { id: "starter-087", hanzi: "商店", pinyin: "shāngdiàn", meaning: "가게", category: "장소" },
  { id: "starter-088", hanzi: "饭馆", pinyin: "fànguǎn", meaning: "식당", category: "장소" },
  { id: "starter-089", hanzi: "医院", pinyin: "yīyuàn", meaning: "병원", category: "장소" },
  { id: "starter-090", hanzi: "车站", pinyin: "chēzhàn", meaning: "역, 정류장", category: "장소" },
  { id: "starter-091", hanzi: "地铁", pinyin: "dìtiě", meaning: "지하철", category: "교통" },
  { id: "starter-092", hanzi: "飞机", pinyin: "fēijī", meaning: "비행기", category: "교통" },
  { id: "starter-093", hanzi: "手机", pinyin: "shǒujī", meaning: "휴대폰", category: "사물" },
  { id: "starter-094", hanzi: "电脑", pinyin: "diànnǎo", meaning: "컴퓨터", category: "사물" },
  { id: "starter-095", hanzi: "水", pinyin: "shuǐ", meaning: "물", category: "음식" },
  { id: "starter-096", hanzi: "茶", pinyin: "chá", meaning: "차", category: "음식" },
  { id: "starter-097", hanzi: "米饭", pinyin: "mǐfàn", meaning: "밥", category: "음식" },
  { id: "starter-098", hanzi: "面条", pinyin: "miàntiáo", meaning: "국수", category: "음식" },
  { id: "starter-099", hanzi: "苹果", pinyin: "píngguǒ", meaning: "사과", category: "음식" },
  { id: "starter-100", hanzi: "钱", pinyin: "qián", meaning: "돈", category: "생활" }
];
